### ISSUE TITLE
Don't clear terminal on flipper disconnect/reload

### ISSUE THREAD

**Issue by kowalski7cc** [flipperdevices/lab.flipper.net#13]
Clear terminal on crash results in making debugging more difficult

**Comment by Slipn3r** [comment]
Won't fix now, requires some deep component rewrite. I'll come back to it with when the times come for session sharing

**Comment by Slipn3r** [comment]
CLI terminal now saves state before reloading (or navigating to another app) and restores it on launch. You can also download the dump containing last 10k lines or clear saved state (aka history).
