### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by benharvie** [flipperdevices/lab.flipper.net#19]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@caioluders) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by Slipn3r** [comment]
Hi, sorry for the long reply. You can contact us at support@flipperdevices.com (added to security.md). Thanks for pointing this out.
