### ISSUE TITLE
Microsoft Edge: WebSerial "works", but stays on connecting

### ISSUE THREAD

**Issue by voltagex** [flipperdevices/lab.flipper.net#20]
Nothing in the logs, I select, pair and connect to the COM port, but the screen stays on "Waiting"

**Comment by Slipn3r** [comment]
Can't reproduce. Please provide OS and browser versions, check if it works in other browsers and record the process if possible with console opened.

**Comment by voltagex** [comment]
Coming back to this - Windows 10.0.19045.2364, Edge 108.0.1462.54, the problem hasn't reoccurred.
