### ISSUE TITLE
Paired yet no access on Linux

### ISSUE THREAD

**Issue by Utopiah** [flipperdevices/lab.flipper.net#29]

**Comment by Utopiah** [comment]
Fixed by using `sudo chmod a+rw /dev/ttyACM1` so I assume missing permissions when running Chromium as a user.

**Comment by Utopiah** [comment]
I imagine setting the right `udev/rules` would work just as well.

**Comment by dogtopus** [comment]
If it works with qFlipper, it sounds like a Chrome bug. Maybe something is not working right with their sandbox implementation that causes it to not obey the access condition of uaccess devices.
