### ISSUE TITLE
SubGhz raw files are displayed wrong after introduction of `shrinkRate`

### ISSUE THREAD

**Issue by sodoku** [flipperdevices/lab.flipper.net#9]
Commit https://github.com/flipperdevices/my.flipper.net/commit/725a6f3b0fd57b0b6e68e47a23bcaf2427407bc0 introduced the `shrinkRate`. With this change it is impossible to detect patterns in my raw subghz files.
On my iPad the `shrinkRate` is `7`. If I understand correctly, this means only every 7th raw value will be displayed. This explains why the ploted data looks very different after this change.

I can add some details in the next days.

**Comment by Slipn3r** [comment]
`shrinkRate` was meant to minimize render lag at certain scales, but was left unfinished. Disabling it completely would require another way to optimise canvas rendering, though making it work correctly would require quite a time too. I'll look into this, thanks. Of course, data should be displayed correctly.

**Comment by Slipn3r** [comment]
Data now only shrinks on zoom values where details are indistinguishable, then shrinkRate is disabled.

**Comment by sodoku** [comment]
Thank you! Everything displays correctly again.
